---
- hosts: all
  vars:
    update_package_manager_cache: false
  vars_files:
    - vars/user.yml
  roles:
    - { role: system, tags: [ 'system' ] }
    - { role: user, tags: [ 'user' ] }
    - { role: zsh, tags: [ 'zsh', 'user-settings' ] }
    - { role: vim, tags: [ 'vim', 'user-settings' ] }
    - { role: screen, tags: [ 'screen', 'user-settings' ] }
