---
- hosts: all
  vars:
    update_package_manager_cache: true
  roles:
    - { role: system, tags: [ 'system' ] }
    - { role: user, tags: [ 'user' ] }
    - { role: zsh, tags: [ 'zsh' ] }
    - { role: vim, tags: [ 'vim' ] }
