---
- name: Add groups
  group: name={{ item }} state=present
  with_items:
    - adm
    - sudo

- name: Add user
  user: name={{ user_name }} password={{ user_password_hash }} groups=adm,sudo append=yes

- name: Add user RSA key
  authorized_key: user={{ user_name }} key="{{ lookup('file', '/home/' + user_name + '/.ssh/id_rsa.pub') }}"

- name: Create sudoers file backup
  command: cp -fa /etc/sudoers /etc/sudoers.bak

- name: Make temporary copy of sudoers file
  command: cp -fa /etc/sudoers /tmp/sudoers

- name: Add sudo group to sudoers
  lineinfile: dest=/tmp/sudoers state=present regexp="^%sudo[\s]+ALL\=\(ALL:ALL\) ALL" line="%sudo ALL=(ALL:ALL) ALL"

- name: Keep ssh-agent env variable through sudo
  lineinfile: dest=/tmp/sudoers state=present regexp="^Defaults[\s]+env_keep\+\=SSH_AUTH_SOCK" line="Defaults env_keep+=SSH_AUTH_SOCK"

- name: Change default visudo editor to vim
  lineinfile: dest=/tmp/sudoers state=present regexp="^Defaults[\s]+editor\=/usr/bin/vim" line="Defaults editor=/usr/bin/vim"

- name: Set custom sudo timestamp for user
  lineinfile: dest=/tmp/sudoers state=present regexp="^Defaults:{{ user_name }}[\s]+timestamp_timeout\=30" line="Defaults:{{ user_name }} timestamp_timeout=30"

- name: Check sudoers file sanity and apply changes
  shell: visudo -q -c -f /tmp/sudoers && mv /tmp/sudoers /etc/sudoers

