---
- name: Update Pacman cache
  pacman: update_cache=yes
  when: update_package_manager_cache

- name: Install system packages (Pacman)
  pacman: name={{ item }} state=present
  with_items: "{{ system_packages }}"
