---
- name: Update APT cache
  apt:  update_cache=yes
  when: update_package_manager_cache

- name: Install system packages (APT)
  apt: name={{ item }} state=latest
  with_items: "{{ system_packages }}"
