---
- name: Load distro specific variables
  include_vars: "{{ ansible_pkg_mgr }}.yml"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: arch.yml
  when: ansible_os_family == "Archlinux"

