---
- name: Update YUM cache
  command: yum makecache
  when: update_package_manager_cache

- name: Install system packages (Yum)
  yum: name={{ item }} state=latest
  with_items: "{{ system_packages }}"
