---
- name: Install screen (Apt)
  apt: name=screen state=latest
  when: ansible_pkg_mgr == "apt"

- name: Install screen (Yum)
  yum: name=screen state=latest
  when: ansible_pkg_mgr == "yum"

- name: Install screen (Pacman)
  pacman: name=screen state=present
  when: ansible_pkg_mgr == "pacman"

- name: deploy .screenrc
  become: true
  become_user: "{{ user_name }}"
  copy: src=screenrc dest="~/.screenrc"
