---
- name: Install vim (Apt)
  apt: name=vim state=latest
  when: ansible_pkg_mgr == "apt"

- name: Install vim (Yum)
  yum: name=vim state=latest
  when: ansible_pkg_mgr == "yum"

- name: Install vim (Pacman)
  pacman: name=vim state=present
  when: ansible_pkg_mgr == "pacman"

- name: deploy .vimrc
  become_user: "{{ user_name }}"
  copy: src=vimrc dest="/home/{{ user_name }}/.vimrc"

- name: Prepare Vim bundles dir
  become_user: "{{ user_name }}"
  file: path={{ item }} state=directory recurse=yes
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundles

- name: Install Vim Pathogen
  become_user: "{{ user_name }}"
  command: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim creates=~/.vim/autoload/pathogen.vim

- name: Install Vim bundles
  become_user: "{{ user_name }}"
  git: repo=https://github.com/{{ item.owner }}/{{ item.repo }}.git dest="/home/{{ user_name }}/.vim/bundles/{{ item.repo }}" update=no
  with_items: "{{ vim_bundles }}"

